{{- define "heart-disease-api.name" -}}
{{- default .Chart.name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "heart-disease-api.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name (include "heart-disease-api.name" .) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
