apiVersion: v2
name: heart-disease-api
description: Helm chart for the Heart Disease MLOps Flask API
type: application
version: 0.1.0          # chart version
appVersion: "1.0.0"     # your app version
